# Generated by Django 5.1.2 on 2024-10-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vendor_Id', models.CharField(max_length=10)),
                ('Vendor_Name', models.CharField(max_length=100)),
                ('Vendor_Phone', models.CharField(max_length=10)),
                ('Customers_Delivering', models.CharField(blank=True, default='Def', max_length=200, null=True)),
                ('Total_Customers', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vendor_ID', models.CharField(max_length=10)),
            ],
        ),
    ]
