# Generated by Django 5.1.2 on 2024-10-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('vendorPortal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorlogin',
            name='Customers_Delivering',
            field=models.ManyToManyField(blank=True, related_name='vendors', to='customers.customer'),
        ),
    ]
