# Generated by Django 5.1.2 on 2024-10-24 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorPortal', '0002_vendorlogin_customers_delivering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='Customers_Delivering',
        ),
        migrations.RemoveField(
            model_name='vendorlogin',
            name='Vendor_ID',
        ),
        migrations.AddField(
            model_name='vendorlogin',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vendorPortal.vendor'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='Vendor_Id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
