# Generated by Django 5.1.2 on 2024-10-24 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorPortal', '0003_remove_vendor_customers_delivering_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorlogin',
            name='Customers_Delivering',
        ),
    ]
