# Generated by Django 5.1.2 on 2024-10-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=400)),
                ('Address_Type', models.CharField(choices=[('Work', 'Work'), ('Home', 'Home'), ('Other', 'Other')], default='Work', max_length=20)),
                ('Phone', models.CharField(max_length=10)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Plan_Type', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('order_completed', models.BooleanField(default=False)),
                ('delivery_confirmation_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
