# Generated by Django 5.1.2 on 2024-10-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('plan_type', models.CharField(max_length=255)),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_phone', models.CharField(max_length=15)),
                ('rating', models.IntegerField()),
                ('feedback', models.TextField()),
            ],
        ),
    ]
