# Generated by Django 5.1.2 on 2024-10-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
